# Generated by Django 4.0.3 on 2022-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.CharField(max_length=15)),
                ('Port', models.IntegerField()),
                ('Success', models.IntegerField()),
                ('Speed', models.IntegerField(verbose_name='Speed in ms')),
                ('Latency', models.IntegerField(verbose_name='Latency in ms')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('Updated', models.DateTimeField(verbose_name='Updated')),
            ],
        ),
    ]
