# Generated by Django 4.0.4 on 2022-06-09 17:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.TextField(default=None, unique=True)),
                ('country', models.TextField(default=None)),
                ('anonymity', models.TextField(default=None)),
                ('success', models.IntegerField(default=0)),
                ('protocol', models.TextField(default='')),
                ('speed', models.FloatField(default=0.0, verbose_name='Speed in seconds')),
                ('updated', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Updated')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('scraper_name', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Proxies',
        ),
    ]
