# Generated by Django 4.0.3 on 2022-04-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxies',
            name='Updated',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='pub_date',
        ),
    ]
