# Generated by Django 4.0.3 on 2022-04-02 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0002_remove_proxies_updated_remove_proxies_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxies',
            name='Latency',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='Speed',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='Success',
        ),
        migrations.AddField(
            model_name='proxies',
            name='Anonymity',
            field=models.CharField(default='transparent', max_length=12),
        ),
        migrations.AddField(
            model_name='proxies',
            name='Country',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='proxies',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 59, 6, 446058), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='VerifiedProxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Success', models.IntegerField()),
                ('Speed', models.IntegerField(verbose_name='Speed in ms')),
                ('Latency', models.IntegerField(verbose_name='Latency in ms')),
                ('Proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxyhandler.proxies')),
            ],
        ),
    ]
