# Generated by Django 4.0.3 on 2022-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0002_remove_proxies_ip_remove_proxies_latency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxies',
            name='anonymity',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proxies',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proxies',
            name='protocol',
            field=models.TextField(default=''),
        ),
    ]
