# Generated by Django 4.0.3 on 2022-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0003_alter_proxies_anonymity_alter_proxies_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxies',
            name='protocol',
        ),
        migrations.AlterField(
            model_name='proxies',
            name='anonymity',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='proxies',
            name='country',
            field=models.TextField(default=None),
        ),
    ]
