# Generated by Django 4.0.3 on 2022-04-02 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0003_remove_proxies_latency_remove_proxies_speed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxies',
            old_name='Anonymity',
            new_name='anonymity',
        ),
        migrations.RenameField(
            model_name='proxies',
            old_name='Country',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='Ip',
        ),
        migrations.RemoveField(
            model_name='proxies',
            name='Port',
        ),
        migrations.AddField(
            model_name='proxies',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='proxies',
            name='socket',
            field=models.CharField(default='', max_length=32),
        ),
    ]
