# Generated by Django 4.0.3 on 2022-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0004_remove_proxies_protocol_alter_proxies_anonymity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='protocol',
            field=models.TextField(default=''),
        ),
    ]
