# Generated by Django 4.0.3 on 2022-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0004_rename_anonymity_proxies_anonymity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='latency',
            field=models.IntegerField(default=0, verbose_name='Latency in ms'),
        ),
        migrations.AddField(
            model_name='proxies',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Speed in ms'),
        ),
        migrations.AddField(
            model_name='proxies',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VerifiedProxies',
        ),
    ]
