# Generated by Django 4.0.4 on 2022-06-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0006_remove_proxies_latency_alter_proxies_speed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proxies',
            new_name='Proxy',
        ),
    ]
