# Generated by Django 4.0.4 on 2022-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0007_rename_proxies_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='speed',
            field=models.FloatField(default=None, verbose_name='Speed in seconds'),
        ),
    ]
