# Generated by Django 4.0.4 on 2022-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyhandler', '0008_alter_proxy_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='speed',
            field=models.FloatField(default=0.0, verbose_name='Speed in seconds'),
        ),
    ]
